//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.GooglePlacesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/GooglePlaces")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceId {
            get {
                return this.PlaceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceIdField, value) != true)) {
                    this.PlaceIdField = value;
                    this.RaisePropertyChanged("PlaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Types {
            get {
                return this.TypesField;
            }
            set {
                if ((object.ReferenceEquals(this.TypesField, value) != true)) {
                    this.TypesField = value;
                    this.RaisePropertyChanged("Types");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GooglePlacesService.IGooglePlaces")]
    public interface IGooglePlaces {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGooglePlaces/GetPointsOfInterest", ReplyAction="http://tempuri.org/IGooglePlaces/GetPointsOfInterestResponse")]
        Frontend.GooglePlacesService.Place[] GetPointsOfInterest(double latitude, double longitude, int radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGooglePlaces/GetPointsOfInterest", ReplyAction="http://tempuri.org/IGooglePlaces/GetPointsOfInterestResponse")]
        System.Threading.Tasks.Task<Frontend.GooglePlacesService.Place[]> GetPointsOfInterestAsync(double latitude, double longitude, int radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGooglePlacesChannel : Frontend.GooglePlacesService.IGooglePlaces, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GooglePlacesClient : System.ServiceModel.ClientBase<Frontend.GooglePlacesService.IGooglePlaces>, Frontend.GooglePlacesService.IGooglePlaces {
        
        public GooglePlacesClient() {
        }
        
        public GooglePlacesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GooglePlacesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GooglePlacesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GooglePlacesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Frontend.GooglePlacesService.Place[] GetPointsOfInterest(double latitude, double longitude, int radius) {
            return base.Channel.GetPointsOfInterest(latitude, longitude, radius);
        }
        
        public System.Threading.Tasks.Task<Frontend.GooglePlacesService.Place[]> GetPointsOfInterestAsync(double latitude, double longitude, int radius) {
            return base.Channel.GetPointsOfInterestAsync(latitude, longitude, radius);
        }
    }
}
