//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=0c197ff0-dbc5-4f2e-8d70-a6f3000ae158.mysql.sequelizer.com;user id=uqdtitqo" +
            "yonhzsuy;password=cBuKtY3scmjwWCiWPEHyvYjTKbbcakC6skNHCkj8UYRhKqTCzSJyiyKmrHarWY" +
            "sZ;database=db0c197ff0dbc54f2e8d70a6f3000ae158")]
        public string db0c197ff0dbc54f2e8d70a6f3000ae158ConnectionString {
            get {
                return ((string)(this["db0c197ff0dbc54f2e8d70a6f3000ae158ConnectionString"]));
            }
        }
    }
}
