//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod_postal,extensao_cod_postal,designacao_postal
        ///3750,011,AGADÃO
        ///3750,012,AGADÃO
        ///3750,013,AGADÃO
        ///3750,014,AGADÃO
        ///3750,015,AGADÃO
        ///3750,016,AGADÃO
        ///3750,017,AGADÃO
        ///3750,018,AGADÃO
        ///3750,019,AGADÃO
        ///3750,996,AGUADA DE BAIXO
        ///3750,031,AGUADA DE BAIXO
        ///3750,033,AGUADA DE BAIXO
        ///3750,035,AGUADA DE BAIXO
        ///3750,041,AGUADA DE CIMA
        ///3750,042,AGUADA DE CIMA
        ///3750,998,AGUADA DE CIMA
        ///3750,043,AGUADA DE CIMA
        ///3750,044,AGUADA DE CIMA
        ///3750,045,AGUADA DE CIMA
        ///3750,046,AGUADA DE CIMA
        ///3750,047,AGUADA DE CIMA
        ///3750, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPData {
            get {
                return ResourceManager.GetString("CPData", resourceCulture);
            }
        }
    }
}
